### ISSUE TITLE
1846 Dark Mode "hides" the closed box on the stock market

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1016]
The closed box is black and cannot be distinguished from the background in the market and in the tooltip below. Perhaps it should have a thin border in a contrasting color?

<img width="378" alt="Screenshot 2020-07-06 17 19 13" src="https://user-images.githubusercontent.com/8732435/86673921-fb52a900-bfac-11ea-9f0a-24c1f57abdd2.png">

**Comment by yzemaze** [comment]
It should already be fixed (https://github.com/tobymao/18xx/pull/981). It should have a border in main font-color and it’s live:
![image](https://user-images.githubusercontent.com/33390595/86729488-d2bec380-c02d-11ea-8d0c-7c31052f8855.png)

=> Check your cache (ctrl+F5 to reload without cache on most browsers)

**Comment by ChrisTheCat** [comment]
Well, there's no F5 button on my Mac. However, I emptied the cache, cleared
all local storage for the domain, and still have the problem. OS X 10.14.6
using Firefox 78.0.1. I also tried it with Google Chrome, which has never
been logged in to 18xx.games on this computer, and got the same result.

**Comment by yzemaze** [comment]
Well, I can’t reproduce the behaviour with any browser on MacOS Catalina on browserstack. They all do render the borders, FF e. g.:
![image](https://user-images.githubusercontent.com/33390595/86788362-5f857380-c066-11ea-8177-a1977c9d2543.png)

… but only when you’re logged in. I guess you aren’t. I’ll fix this.

**Comment by ChrisTheCat** [comment]
I experimented and changed my main font color to red and my alternative
font color to green. The box is now outlined in red.

When I reset to defaults on a Mac with Dark Mode enabled, the box outline
disappeared again.

**Comment by ChrisTheCat** [comment]
p.s. my employer won't let me run Catalina yet, I'm still on Mojave. (Well,
I could run Catalina, but then I wouldn't be able to connect to most of my
work apps/sites.)

**Comment by yzemaze** [comment]
If you reset default font-color and therefore border-color in this case should be gainsboro (#dcdcdc) if prefers-color-scheme is set to dark.
I don’t think the exact OS version makes a diff. (I just hadn’t checked which version number == Catalina before. Now I know.)

**Comment by yzemaze** [comment]
So this works if not logged-in. I don’t know if it’ll make a diff for you @ChrisTheCat

**Comment by ChrisTheCat** [comment]
Not sure what being not logged-in has to do with it. I've been logged in
for all my tests. But anyway, it's apparently an anomaly and really not
that important.

**Comment by tobymao** [comment]
i can't repro this, on cataline, it looks good to me

**Comment by tobymao** [comment]
ah, looks like it's broken in safari

**Comment by ChrisTheCat** [comment]
And perhaps in Firefox, which is what I'm using.
