### ISSUE TITLE
[1828.games] Auto Buy Shares cannot handle merged shell corporations correctly

### ISSUE THREAD

**Issue by Andy-0711** [tobymao/18xx#5408]
Example: https://18xx.games/game/41941

If you want to use Auto Buy Share after a merger it allows you to select a merged corporation but after selection it shows the old unmerged corporation and allows you for example "buy until float" even if the merged corporation is floated. 

I didn't try to use Auto Buy during the game because I didn't want to risk to crush the game so I don't know what shares would have been bought.

So it might be only a display error but it also might be combined with a follow-up bug if ignored.

Attention: Sometimes (I guess the first time you open "auto") a merged corporation will show up correctly until you select another corporation. 

**How to Reproduce the Bug?**
Open the saved game and click "auto" AND select a corporation.

What steps cause the unexpected behavior?
Try to auto buy shares of any merged cormporation during any phase of the game.

**Which Browser / Platform?**
Chrome Version 90.0.4430.212 (Offizieller Build) (64-Bit)
Desktop: Microsoft Windows [Version 10.0.19043.985]; Microsoft Windows [Version 10.0.17763.1935]; Phone (Android)

**Comment by Andy-0711** [comment]
Maybe connected to https://github.com/tobymao/18xx/issues/5333

**Comment by Andy-0711** [comment]
I expect the problem is that there are 2 corporations with the same name: the old (unmerged) and the new (merged). So this problem is basically the same as in https://github.com/tobymao/18xx/issues/5310. These problems should be resolved together, I guess (together with https://github.com/tobymao/18xx/issues/5333).

**Comment by crericha** [comment]
What I think is going on is the original two companies weren't closed using @game.close_corporation, so while the corporation itself was marked as closed, it was still hanging around.

I pushed a candidate fix that deletes the shares and the corporations from the game. I didn't have an easy way to test it though. Could someone try it out in a day or two when its deployed?

**Comment by crericha** [comment]
The potential fix is deployed. Can someone volunteer to verify?

**Comment by crericha** [comment]
Closing as this should be fixed. Reopen is still a problem.
