### ISSUE TITLE
[18GB] game stuck w/ error: undefined method `owner' for nil" 

### ISSUE THREAD

**Issue by edbessiere** [tobymao/18xx#9877]
Game will not load

(https://18xx.games/game/136880?action=830)

game will not load. We were in final round. 18GB- so it ends when there are no trains to buy or when you get a stock to the top of the track.
We had two companies which did not have CEO's and it was time for one to run. It went into the NPC's turn and would no longer load the game.

I am using Safari.

**Comment by benjaminxscott** [comment]
>undefined method `owner' for nil"

**Comment by edbessiere** [comment]
owner ndmvkilroy

**Comment by edbessiere** [comment]
Id: 136880
Description: Sharkheads
Players: [Lawk3t](https://18xx.games/profile/15620), [frodobro](https://18xx.games/profile/15708), [ndmvkilroy](https://18xx.games/profile/15621), [WESTalan](https://18xx.games/profile/15618)
Round: Operating 8

**Comment by benjaminxscott** [comment]
I have a patch for this, it's related to the insolvent LYR leasing a "notional" train

**Comment by edbessiere** [comment]
I'm glad to hear that there is hope. Looking forward to being able to finish.

**Comment by benjaminxscott** [comment]
fwiw here's the results
```
[13:03] Market operates LYR
[13:03] LYR skips lay track
-- 2023-11-15 --
[14:28] LYR runs a 6X train for £330: H15-H9-F5-G4-I2-K0+£90
[14:28] LYR withholds £330
[14:28] LYR's share price moves left from £55 to £50
[14:28] LYR passes buy trains
[14:28] -- Game over: frodobro (£5075), WESTalan (£5065), ndmvkilroy (£4006), Lawk3t (£1416) --
```

**Comment by edbessiere** [comment]
Thanks for final score. A buzzer beater of a game.

**Comment by slapphappyjazz** [comment]
So, has this been fixed now?  Should this bug be closed?

**Comment by edbessiere** [comment]
It can be closed. Not sure if the bug is fixed for future games. But the person whom assisted was able to finish the specific game for us.Thanks,Ed BessiereOn Dec 13, 2023, at 4:48 PM, slapphappyjazz ***@***.***> wrote:﻿
So, has this been fixed now?  Should this bug be closed?

**Comment by benjaminxscott** [comment]
the underlying issue isn't fixed, my PR wasn't merged due to breaking tests and I didn't have bandwidth over the holidays to get it to pass tests
